## Gene test suite — run all test modules
{.warning[UnusedImport]: off.}
include test_reader
include test_reader_wrap
include test_source_index
include test_viewer
include test_viewer_editor
include test_vterm
include test_pty_process
include test_terminal_session
include test_values
include test_buffers
include test_bound_call
include test_callable_reflection
include test_pipeline
include test_unify_callable
include test_capabilities
include test_vm
include test_modules
include test_package
include test_system_dependency
include test_build
include test_web_modules
include test_match
include test_errors
include test_error_handling
include test_generators
include test_testing
include test_types
include test_protocols
include test_self_type
include test_nil_void
include test_native_api
include test_native_callbacks
include test_logging
include test_cli
include test_lsp
include test_http_server
include test_http_client
