import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const root = process.cwd();
const domPath = path.join(root, "node_modules", "typescript", "lib", "lib.dom.d.ts");
if (!fs.existsSync(domPath)) {
  throw new Error("TypeScript lib.dom.d.ts is missing; run npm install first");
}

// This allowlist is deliberately small. The generator verifies that every
// admitted member still exists in the pinned lib.dom.d.ts and emits only the
// ABI shapes the Gene web profile can represent. Overloads, conditional types,
// mapped types, and generic callbacks remain outside the binding contract.
const supported = new Map([
  ["EventTarget", ["addEventListener", "removeEventListener"]],
  ["Node", ["appendChild", "removeChild"]],
  ["Element", ["setAttribute", "removeAttribute"]],
  ["Document", ["createElement", "createTextNode", "createDocumentFragment"]],
]);

const source = ts.createSourceFile(
  domPath,
  fs.readFileSync(domPath, "utf8"),
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
);
const interfaces = new Map();
for (const statement of source.statements) {
  if (ts.isInterfaceDeclaration(statement)) interfaces.set(statement.name.text, statement);
}

const manifest = {
  generated_by: "tools/generate_dom_bindings.mjs",
  typescript: ts.version,
  source: "lib.dom.d.ts",
  policy: "explicit allowlist; unsupported TypeScript shapes are rejected",
  interfaces: {},
};
for (const [interfaceName, memberNames] of supported) {
  const declaration = interfaces.get(interfaceName);
  if (!declaration) throw new Error(`lib.dom.d.ts no longer declares ${interfaceName}`);
  manifest.interfaces[interfaceName] = {};
  for (const memberName of memberNames) {
    const matches = declaration.members.filter(
      (member) => ts.isMethodSignature(member) && member.name.getText(source) === memberName,
    );
    if (matches.length === 0) {
      throw new Error(`lib.dom.d.ts no longer declares ${interfaceName}.${memberName}`);
    }
    manifest.interfaces[interfaceName][memberName] = {
      overloads_in_lib_dom: matches.length,
      gene_abi: "Any boundary with generated checked callback adapters",
    };
  }
}

const declarationText = `// Generated by tools/generate_dom_bindings.mjs from TypeScript ${ts.version}.
// This is the intentionally supported subset, not a claim to model all lib.dom.d.ts.
export interface GeneDomBindings {
  create_element(document: Document, tag_name: string): Element;
  create_text_node(document: Document, text: string): Text;
  create_document_fragment(document: Document): DocumentFragment;
  append_child(parent: Node, child: Node): Node;
  remove_child(parent: Node, child: Node): Node;
  set_attribute(element: Element, name: string, value: string): void;
  remove_attribute(element: Element, name: string): void;
  add_event_listener(target: EventTarget, type: string, listener: (event: Event) => void): void;
  remove_event_listener(target: EventTarget, type: string, listener: (event: Event) => void): void;
}
`;

fs.mkdirSync(path.join(root, "web"), { recursive: true });
fs.writeFileSync(
  path.join(root, "web", "gene_dom_bindings.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
fs.writeFileSync(path.join(root, "web", "gene_dom.generated.d.ts"), declarationText);
console.log("generated web/gene_dom_bindings.json and web/gene_dom.generated.d.ts");
