#!/usr/bin/env python3
"""Generate or verify the Gene harness core-event persistence catalog."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "examples/gene-harness/events.catalog"
TARGET = ROOT / "examples/gene-harness/src/generated_event_catalog.gene"


def render() -> str:
    schema_fields = {
        "text": ["type", "text"],
        "turn_start": ["type", "turn"],
        "turn_end": ["type", "turn", "reason", "synthetic"],
        "composition_changed": [
            "type", "entry", "operation", "previous_digest", "new_digest",
            "revision", "session", "turn",
        ],
        "plugin_state": ["type", "plugin", "state_version", "state"],
    }
    rows: list[tuple[str, int, bool, str]] = []
    for number, raw in enumerate(SOURCE.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if (len(parts) != 4 or parts[2] not in {"required", "ignorable"}
                or parts[3] not in schema_fields):
            raise SystemExit(
                f"{SOURCE}:{number}: expected NAME VERSION "
                "required|ignorable SCHEMA"
            )
        name, version_text, policy, schema = parts
        try:
            version = int(version_text)
        except ValueError as error:
            raise SystemExit(f"{SOURCE}:{number}: version must be an integer") from error
        if version <= 0:
            raise SystemExit(f"{SOURCE}:{number}: version must be positive")
        rows.append((name, version, policy == "ignorable", schema))

    if len({name for name, _, _, _ in rows}) != len(rows):
        raise SystemExit(f"{SOURCE}: duplicate event name")

    rendered = [
        "# Generated by tools/generate_harness_event_catalog.py; do not edit by hand.",
        "",
        "(mod generated_event_catalog)",
        "",
        "(fn require_event_fields [payload, names, event_name]",
        "  (for name in names",
        "    (if (== (payload .get name) void)",
        "      ($panic $\"event ${event_name} requires ${name}\")))",
        "  payload)",
        "",
    ]
    for schema, fields in schema_fields.items():
        rendered.extend([
            f"(fn validate_{schema}_event [payload]",
            "  (require_event_fields payload ["
            + " ".join(f'\"{field}\"' for field in fields)
            + f'] \"{schema}\"))',
            "",
        ])
    rendered.append("(var core_event_types")
    for index, (name, version, ignorable, schema) in enumerate(rows):
        prefix = "  #[" if index == 0 else "    "
        suffix = "]" if index == len(rows) - 1 else ""
        rendered.append(
            f'{prefix}#{{^name "{name}" ^version {version} '
            f'^ignorable {str(ignorable).lower()} '
            f'^origin "core" ^owner "core" '
            f'^schema validate_{schema}_event}}{suffix}'
        )
    rendered[-1] += ")"
    return "\n".join(rendered) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            raise SystemExit("generated harness event catalog is stale")
        print("harness event catalog: current")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(TARGET.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
