#!/usr/bin/env python3
"""Run the excluded experiment-4 version-3 component-wise difficulty pilot.

Each task starts a fresh qualified-model conversation. The model identifies one
ordered workflow component at a time and proposes exactly three catalog
operations for it. The public checker compares that candidate against only the
component's three already-public demonstrations, so every checker response is a
deterministic function of public data and the model's own arguments. The single
hidden comparison in an episode is the terminal submission. Pilot seeds never
enter treatment.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import resource
import subprocess
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OLLAMA_URL = "http://127.0.0.1:11434"
EXPORTER = (
    ROOT
    / "examples/general_intelligence/src/component_workflow_pilot_export.gene"
)
SUBJECT = (
    ROOT / "examples/general_intelligence/src/component_workflow_subject.gene"
)
BASE_SUBJECT = (
    ROOT / "examples/general_intelligence/src/latent_workflow_subject.gene"
)
INTERPRETER = ROOT / "examples/general_intelligence/src/library_induction.gene"
OPERATIONS = [
    "tail",
    "init",
    "reverse",
    "rotate_left",
    "rotate_right",
    "map_add_one",
    "map_sub_one",
    "map_double",
    "map_negate",
    "keep_even",
    "keep_odd",
    "duplicate_each",
]
OPERATION_HELP = {
    "tail": "remove the first item",
    "init": "remove the last item",
    "reverse": "reverse item order",
    "rotate_left": "move the first item to the end",
    "rotate_right": "move the last item to the front",
    "map_add_one": "add one to every item",
    "map_sub_one": "subtract one from every item",
    "map_double": "double every item",
    "map_negate": "negate every item",
    "keep_even": "keep only even items",
    "keep_odd": "keep only odd items",
    "duplicate_each": "duplicate every item in place",
}
COMPONENT_OPERATION_COUNT = 3
PUBLIC_TASK_FIELDS = {
    "task_id",
    "instruction",
    "components_in_order",
    "query_input",
    "attempts_per_component",
}
HIDDEN_TASK_FIELDS = {
    "expected",
    "component_operations",
    "chain_values",
    "semantic_signatures",
    "admissible_candidate_counts",
}
CHECKER_RESPONSE_FIELDS = {
    "status",
    "components_completed",
    "components_remaining",
    "current",
    "attempts_remaining",
}
SYSTEM_PROMPT = """Identify demonstration-defined list workflows one component
at a time. Every component is generated by exactly three operations from this
catalog:
{catalog}
Work through the listed components in the given order. For the current
component, infer its three operations from its three demonstrations and send
them with apply_workflow_candidate. The checker runs your three operations on
those same three public demonstrations and nothing else. If all three
reproduce, the component is accepted and the host applies your operations to
the query list. Otherwise you get status inconsistent and one further attempt;
when a component's attempt budget is spent the task ends.
Call submit_result once, after the last component is accepted. It is final: the
first submit_result ends the task whether the answer is right or wrong.
Several tool calls may share one response. Your response is cut off at a hard
generation limit, so keep reasoning short and return a tool call in every
response; a response with no tool call wastes a round.""".format(
    catalog="; ".join(f"{name}: {OPERATION_HELP[name]}" for name in OPERATIONS)
)
SILENT_ROUND_REMINDER = (
    "Your previous response reached the generation limit without a tool call. "
    "Do not restate your reasoning. Send apply_workflow_candidate now for the "
    "first component that has not been accepted, using your best three "
    "operations."
)
APPLY_TOOL = {
    "type": "function",
    "function": {
        "name": "apply_workflow_candidate",
        "description": (
            "Propose the three catalog operations for the current workflow "
            "component. Checked against that component's three public "
            "demonstrations only."
        ),
        "parameters": {
            "type": "object",
            "additionalProperties": False,
            "required": ["workflow_id", "operations"],
            "properties": {
                "workflow_id": {"type": "string"},
                # The flat enumerated string array is the only candidate shape
                # the pinned model accepted during adapter qualification; keep
                # length enforcement in the description and the host rather
                # than adding schema keywords that were never qualified.
                "operations": {
                    "type": "array",
                    "description": "Exactly three catalog operations, in order.",
                    "items": {"type": "string", "enum": OPERATIONS},
                },
            },
        },
    },
}
SUBMIT_TOOL = {
    "type": "function",
    "function": {
        "name": "submit_result",
        "description": (
            "Submit the host-maintained query list for the final exact check. "
            "This ends the task."
        ),
        "parameters": {
            "type": "object",
            "additionalProperties": False,
            "properties": {},
        },
    },
}
TOOLS = [APPLY_TOOL, SUBMIT_TOOL]


class PilotError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def post_json(path: str, payload: dict[str, Any], timeout: int = 300) -> dict[str, Any]:
    request = urllib.request.Request(
        OLLAMA_URL + path,
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read().decode("utf-8"))


def get_json(path: str) -> dict[str, Any]:
    with urllib.request.urlopen(OLLAMA_URL + path, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def apply_operation(value: list[int], operation: str) -> list[int]:
    if operation == "tail":
        return value[1:] if len(value) > 1 else []
    if operation == "init":
        return value[:-1] if len(value) > 1 else []
    if operation == "reverse":
        return list(reversed(value))
    if operation == "rotate_left":
        return value[1:] + value[:1] if len(value) > 1 else list(value)
    if operation == "rotate_right":
        return value[-1:] + value[:-1] if len(value) > 1 else list(value)
    if operation == "map_add_one":
        return [item + 1 for item in value]
    if operation == "map_sub_one":
        return [item - 1 for item in value]
    if operation == "map_double":
        return [item * 2 for item in value]
    if operation == "map_negate":
        return [-item for item in value]
    if operation == "keep_even":
        return [item for item in value if item % 2 == 0]
    if operation == "keep_odd":
        return [item for item in value if item % 2 != 0]
    if operation == "duplicate_each":
        return [copy for item in value for copy in (item, item)]
    raise PilotError("unknown operation reached the exact executor")


def apply_program(value: list[int], operations: list[str]) -> list[int]:
    result = list(value)
    for operation in operations:
        result = apply_operation(result, operation)
    return result


def enumerate_programs(maximum_length: int = COMPONENT_OPERATION_COUNT) -> list[tuple]:
    programs: list[tuple] = [()]
    frontier: list[tuple] = [()]
    for _ in range(maximum_length):
        extended = [prefix + (name,) for prefix in frontier for name in OPERATIONS]
        programs.extend(extended)
        frontier = extended
    return programs


ALL_PROGRAMS = enumerate_programs()


def admissible_programs(demonstrations: list[dict[str, Any]]) -> list[tuple]:
    """Every program of length zero through three consistent with the public
    demonstrations. This is exactly the set a public checker would accept."""
    consistent = []
    for program in ALL_PROGRAMS:
        if all(
            apply_program(demonstration["input"], list(program))
            == demonstration["output"]
            for demonstration in demonstrations
        ):
            consistent.append(program)
    return consistent


def valid_integer_list(value: Any) -> bool:
    return isinstance(value, list) and all(type(item) is int for item in value)


class PublicChecker:
    """The model-facing checker. Constructed from the public projection alone;
    it holds no verifier-owned field and reads none."""

    def __init__(self, projection: dict[str, Any]) -> None:
        if set(projection) != PUBLIC_TASK_FIELDS:
            raise PilotError("public checker received a non-public projection")
        self.components = projection["components_in_order"]
        self.attempts_per_component = projection["attempts_per_component"]
        self.current = list(projection["query_input"])
        self.component_index = 0
        self.attempts_used = 0
        self.checker_attempts = 0
        self.accepted_candidates: list[list[str]] = []

    @property
    def finished(self) -> bool:
        return self.component_index >= len(self.components)

    def well_formed(self, workflow_id: Any, operations: Any) -> bool:
        return (
            not self.finished
            and isinstance(workflow_id, str)
            and workflow_id == self.components[self.component_index]["workflow_id"]
            and isinstance(operations, list)
            and len(operations) == COMPONENT_OPERATION_COUNT
            and all(
                isinstance(item, str) and item in OPERATIONS for item in operations
            )
        )

    def apply_candidate(self, workflow_id: Any, operations: Any) -> dict[str, Any]:
        if not self.well_formed(workflow_id, operations):
            return {"status": "invalid_request"}
        component = self.components[self.component_index]
        self.checker_attempts += 1
        self.attempts_used += 1
        candidate = list(operations)
        consistent = all(
            apply_program(demonstration["input"], candidate)
            == demonstration["output"]
            for demonstration in component["demonstrations"]
        )
        if consistent:
            self.current = apply_program(self.current, candidate)
            self.component_index += 1
            self.attempts_used = 0
            self.accepted_candidates.append(candidate)
            return {
                "status": "accepted",
                "components_completed": self.component_index,
                "components_remaining": len(self.components) - self.component_index,
                "current": self.current,
            }
        if self.attempts_used >= self.attempts_per_component:
            return {"status": "attempts_exhausted"}
        return {
            "status": "inconsistent",
            "attempts_remaining": self.attempts_per_component - self.attempts_used,
        }


class HiddenVerifier:
    """Owns the one hidden comparison in an episode and counts every read."""

    def __init__(self, expected: list[int]) -> None:
        self._expected = list(expected)
        self.reads = 0

    def submit(self, value: list[int]) -> bool:
        self.reads += 1
        return value == self._expected


def load_tasks(
    catalog_seed: int,
    order_seed: int,
    count: int,
    composition_arity: int,
) -> tuple[list[dict[str, Any]], float]:
    started = time.monotonic()
    completed = subprocess.run(
        [
            str(ROOT / "bin/gene"),
            "run",
            str(EXPORTER),
            str(catalog_seed),
            str(order_seed),
            str(count),
            str(composition_arity),
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    wall_seconds = time.monotonic() - started
    if completed.returncode != 0:
        raise PilotError((completed.stderr or completed.stdout).strip())
    expected_fields = {
        "schema",
        "id",
        "instruction",
        "input",
        "attempts_per_component",
        "components",
        "expected",
        "component_operations",
        "chain_values",
        "semantic_signatures",
        "admissible_candidate_counts",
    }
    tasks: list[dict[str, Any]] = []
    admissible_cache: dict[str, list[tuple]] = {}
    demonstrations_by_workflow: dict[str, Any] = {}
    for line in completed.stdout.splitlines():
        try:
            task = json.loads(line)
        except json.JSONDecodeError as exc:
            raise PilotError("task exporter emitted invalid JSON") from exc
        if not isinstance(task, dict) or set(task) != expected_fields:
            raise PilotError("task exporter emitted an unexpected schema")
        if task["schema"] != 3 or not isinstance(task["id"], str):
            raise PilotError("task exporter identity is invalid")
        if not isinstance(task["instruction"], str) or not task["instruction"]:
            raise PilotError("task instruction is invalid")
        if task["attempts_per_component"] != 2:
            raise PilotError("attempt budget is not the preregistered value")
        if not valid_integer_list(task["input"]) or not valid_integer_list(
            task["expected"]
        ):
            raise PilotError("task query values are invalid")
        components = task["components"]
        if not isinstance(components, list) or len(components) != composition_arity:
            raise PilotError("task has the wrong component count")
        programs = task["component_operations"]
        if not isinstance(programs, list) or len(programs) != composition_arity:
            raise PilotError("component program count is invalid")
        chain = task["chain_values"]
        if not isinstance(chain, list) or len(chain) != composition_arity + 1:
            raise PilotError("chain value count is invalid")
        if any(not valid_integer_list(value) for value in chain):
            raise PilotError("chain values are invalid")
        if chain[0] != task["input"] or chain[-1] != task["expected"]:
            raise PilotError("chain endpoints disagree with the task")
        signatures = task["semantic_signatures"]
        if not isinstance(signatures, list) or len(signatures) != composition_arity:
            raise PilotError("semantic signature count is invalid")
        if any(not isinstance(item, str) or not item for item in signatures):
            raise PilotError("semantic signature is invalid")
        counts = task["admissible_candidate_counts"]
        if not isinstance(counts, list) or len(counts) != composition_arity:
            raise PilotError("admissible candidate count list is invalid")
        for index, component in enumerate(components):
            if not isinstance(component, dict) or set(component) != {
                "workflow_id",
                "demonstrations",
            }:
                raise PilotError("workflow component schema is invalid")
            workflow_id = component["workflow_id"]
            if not isinstance(workflow_id, str):
                raise PilotError("workflow identity is invalid")
            demonstrations = component["demonstrations"]
            if not isinstance(demonstrations, list) or len(demonstrations) != 3:
                raise PilotError("workflow must expose exactly three demonstrations")
            for demonstration in demonstrations:
                if not isinstance(demonstration, dict) or set(demonstration) != {
                    "input",
                    "output",
                }:
                    raise PilotError("demonstration schema is invalid")
                if not valid_integer_list(
                    demonstration["input"]
                ) or not valid_integer_list(demonstration["output"]):
                    raise PilotError("demonstration values are invalid")
            known = demonstrations_by_workflow.setdefault(workflow_id, demonstrations)
            if known != demonstrations:
                raise PilotError("a workflow exposed two different public packs")
            program = programs[index]
            if (
                not isinstance(program, list)
                or len(program) != COMPONENT_OPERATION_COUNT
                or any(operation not in OPERATIONS for operation in program)
            ):
                raise PilotError("component program is invalid")
            for demonstration in demonstrations:
                if (
                    apply_program(demonstration["input"], program)
                    != demonstration["output"]
                ):
                    raise PilotError("Python executor disagrees with a demonstration")
            if apply_program(chain[index], program) != chain[index + 1]:
                raise PilotError("Python executor disagrees with a chain value")
            if chain[index + 1] == chain[index]:
                raise PilotError("a component does not change its intermediate value")
            if workflow_id not in admissible_cache:
                admissible_cache[workflow_id] = admissible_programs(demonstrations)
            candidates = admissible_cache[workflow_id]
            if not candidates:
                raise PilotError("a component has no admissible candidate")
            if counts[index] != len(candidates):
                raise PilotError(
                    "Gene and Python disagree on the admissible candidate count"
                )
            if tuple(program) not in candidates:
                raise PilotError("the canonical program is not publicly admissible")
            for candidate in candidates:
                if apply_program(chain[index], list(candidate)) != chain[index + 1]:
                    raise PilotError(
                        "public-checker soundness fails for an exported component"
                    )
        if task["input"] == task["expected"] or not task["expected"]:
            raise PilotError("task query is ineffective")
        tasks.append(task)
    if len(tasks) != count:
        raise PilotError("task exporter returned the wrong task count")
    return tasks, wall_seconds


def public_projection(task: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": task["id"],
        "instruction": task["instruction"],
        "components_in_order": task["components"],
        "query_input": task["input"],
        "attempts_per_component": task["attempts_per_component"],
    }


def public_user_message(task: dict[str, Any]) -> str:
    return canonical_json(public_projection(task))


def round_ceiling(composition_arity: int) -> int:
    return 3 * composition_arity + 3


def call_shape(call: Any) -> tuple[Any, Any]:
    function = call.get("function") if isinstance(call, dict) else None
    name = function.get("name") if isinstance(function, dict) else None
    arguments = function.get("arguments") if isinstance(function, dict) else None
    return name, arguments


def schema_conformant(name: Any, arguments: Any) -> bool:
    if name == "apply_workflow_candidate":
        return (
            isinstance(arguments, dict)
            and set(arguments) == {"workflow_id", "operations"}
            and isinstance(arguments["workflow_id"], str)
            and isinstance(arguments["operations"], list)
            and len(arguments["operations"]) == COMPONENT_OPERATION_COUNT
            and all(
                isinstance(item, str) and item in OPERATIONS
                for item in arguments["operations"]
            )
        )
    if name == "submit_result":
        return isinstance(arguments, dict) and not arguments
    return False


def chat_payload(
    model: str,
    messages: list[dict[str, Any]],
    num_predict: int,
    think: str | None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "tools": TOOLS,
        "stream": False,
        "keep_alive": "10m",
        "options": {
            "temperature": 0,
            "seed": 20260809,
            "num_ctx": 32768,
            "num_predict": num_predict,
        },
    }
    # Reasoning-effort control, added for version 4. Omitted entirely at default
    # effort so a default-effort request stays byte-identical to the version-3
    # runs this harness already produced.
    if think is not None:
        payload["think"] = think
    return payload


def run_task(
    model: str,
    task: dict[str, Any],
    max_rounds: int,
    silent_round_cap: int,
    num_predict: int,
    think: str | None = None,
) -> dict[str, Any]:
    user_message = public_user_message(task)
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ]
    checker = PublicChecker(public_projection(task))
    verifier = HiddenVerifier(task["expected"])
    accepted = False
    end_reason = "round_limit"
    silent_rounds = 0
    tool_calls = 0
    schema_conformant_calls = 0
    prompt_tokens = 0
    generated_tokens = 0
    rounds = 0
    started = time.monotonic()
    finished = False
    for rounds in range(1, max_rounds + 1):
        response = post_json(
            "/api/chat", chat_payload(model, messages, num_predict, think)
        )
        prompt_tokens += int(response.get("prompt_eval_count", 0))
        generated_tokens += int(response.get("eval_count", 0))
        message = response.get("message")
        if not isinstance(message, dict):
            end_reason = "empty_response"
            break
        messages.append(message)
        calls = message.get("tool_calls") or []
        if not isinstance(calls, list) or not calls:
            silent_rounds += 1
            if silent_rounds > silent_round_cap:
                end_reason = "silent_round_limit"
                break
            messages.append({"role": "user", "content": SILENT_ROUND_REMINDER})
            continue
        for call in calls:
            tool_calls += 1
            name, arguments = call_shape(call)
            conformant = schema_conformant(name, arguments)
            schema_conformant_calls += int(conformant)
            if name == "apply_workflow_candidate":
                if conformant:
                    result = checker.apply_candidate(
                        arguments["workflow_id"], arguments["operations"]
                    )
                else:
                    result = {"status": "invalid_request"}
                if result["status"] == "attempts_exhausted":
                    end_reason = "attempts_exhausted"
                    finished = True
            elif name == "submit_result" and conformant:
                accepted = verifier.submit(checker.current)
                result = {"status": "accepted" if accepted else "rejected"}
                end_reason = "submitted"
                finished = True
            else:
                result = {"status": "invalid_request"}
            if set(result) - CHECKER_RESPONSE_FIELDS:
                raise PilotError("a tool response carried an undeclared field")
            messages.append(
                {
                    "role": "tool",
                    "tool_name": name if isinstance(name, str) else "invalid_tool",
                    "content": json.dumps(result, sort_keys=True),
                }
            )
            if finished:
                break
        if finished:
            break
    if verifier.reads > 1:
        raise PilotError("the hidden expected output was read more than once")
    return {
        "id": task["id"],
        "accepted": accepted,
        "end_reason": end_reason,
        "rounds": rounds,
        "silent_rounds": silent_rounds,
        "tool_calls": tool_calls,
        "schema_conformant_calls": schema_conformant_calls,
        "checker_attempts": checker.checker_attempts,
        "components_completed": checker.component_index,
        "components_total": len(task["components"]),
        "hidden_reads": verifier.reads,
        "prompt_tokens": prompt_tokens,
        "generated_tokens": generated_tokens,
        "wall_seconds": time.monotonic() - started,
        "model_input_sha256": hashlib.sha256(user_message.encode("utf-8")).hexdigest(),
        "accepted_candidates": checker.accepted_candidates,
        "canonical_component_operations": task["component_operations"],
        "final_value_sha256": hashlib.sha256(
            canonical_json(checker.current).encode()
        ).hexdigest(),
    }


def peak_rss_bytes() -> int:
    value = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return int(value if platform.system() == "Darwin" else value * 1024)


def self_test(tasks: list[dict[str, Any]], composition_arity: int) -> None:
    if PUBLIC_TASK_FIELDS & HIDDEN_TASK_FIELDS:
        raise PilotError("the public and hidden field sets overlap")
    tool_names = {tool["function"]["name"] for tool in TOOLS}
    if tool_names != {"apply_workflow_candidate", "submit_result"}:
        raise PilotError("the model-facing tool set is not the declared pair")
    promotion_words = ("promot", "receipt", "replay", "skill")
    surface = json.dumps(TOOLS) + SYSTEM_PROMPT + SILENT_ROUND_REMINDER
    for word in promotion_words:
        if word in surface.lower():
            raise PilotError(f"the model-facing surface mentions '{word}'")

    noncanonical_advances = 0
    inconsistent_checked = 0
    for task in tasks:
        projection = public_projection(task)
        if set(projection) != PUBLIC_TASK_FIELDS:
            raise PilotError("the public projection changed shape")
        message = public_user_message(task)
        for field in HIDDEN_TASK_FIELDS:
            if field in message:
                raise PilotError("the public projection names a hidden field")
        for signature in task["semantic_signatures"]:
            if signature in message:
                raise PilotError("the public projection leaked a semantic signature")
        for value in task["chain_values"][1:]:
            if canonical_json(value) in message:
                raise PilotError("the public projection leaked a chain value")

        # 1 and 4: a behavior-equivalent non-canonical candidate advances a
        # component, and the whole accepted transcript is reproducible from
        # public data alone.
        checker = PublicChecker(projection)
        verifier = HiddenVerifier(task["expected"])
        for index, component in enumerate(task["components"]):
            candidates = admissible_programs(component["demonstrations"])
            canonical = tuple(task["component_operations"][index])
            chosen = next(
                (item for item in candidates if item != canonical), canonical
            )
            if chosen != canonical:
                noncanonical_advances += 1
            result = checker.apply_candidate(component["workflow_id"], list(chosen))
            if result["status"] != "accepted":
                raise PilotError("an admissible candidate failed to advance")
            if set(result) - CHECKER_RESPONSE_FIELDS:
                raise PilotError("an accepted response carried an undeclared field")
            if result["current"] != task["chain_values"][index + 1]:
                raise PilotError("an accepted candidate diverged from the chain")
            if verifier.reads != 0:
                raise PilotError("the public checker read the hidden output")
        if not checker.finished:
            raise PilotError("the public path did not complete every component")
        if not verifier.submit(checker.current):
            raise PilotError("the public path did not reach the hidden output")
        if verifier.reads != 1:
            raise PilotError("the hidden output was not read exactly once")

        # 2 and 3: an inconsistent candidate returns only the generic status,
        # advances nothing, and the attempt budget is exact.
        budget = task["attempts_per_component"]
        checker = PublicChecker(projection)
        first = task["components"][0]
        wrong = ["reverse", "reverse", "reverse"]
        if tuple(wrong) in admissible_programs(first["demonstrations"]):
            wrong = ["tail", "tail", "tail"]
        for attempt in range(1, budget + 1):
            result = checker.apply_candidate(first["workflow_id"], wrong)
            inconsistent_checked += 1
            if attempt < budget:
                if result != {
                    "status": "inconsistent",
                    "attempts_remaining": budget - attempt,
                }:
                    raise PilotError("an inconsistent candidate leaked detail")
            elif result != {"status": "attempts_exhausted"}:
                raise PilotError("the attempt budget is not exact")
            if checker.component_index != 0:
                raise PilotError("an inconsistent candidate advanced a component")
            if checker.current != task["input"]:
                raise PilotError("an inconsistent candidate changed the value")

        # Out-of-order and malformed requests are refused generically and
        # consume no attempt.
        checker = PublicChecker(projection)
        last = task["components"][-1]
        malformed = [
            (last["workflow_id"], list(task["component_operations"][-1])),
            (first["workflow_id"], ["tail", "tail"]),
            (first["workflow_id"], ["tail", "tail", "not_an_operation"]),
            (first["workflow_id"], "tail"),
        ]
        for workflow_id, operations in malformed:
            if checker.apply_candidate(workflow_id, operations) != {
                "status": "invalid_request"
            }:
                raise PilotError("a malformed request was not generically refused")
        if checker.checker_attempts != 0 or checker.component_index != 0:
            raise PilotError("a malformed request consumed an attempt")

    if noncanonical_advances == 0:
        raise PilotError("no behavior-equivalent non-canonical candidate was exercised")
    print(
        "component workflow pilot self-test: "
        f"tasks={len(tasks)} arity={composition_arity} "
        f"round_ceiling={round_ceiling(composition_arity)} "
        f"public_hidden_fields=0 noncanonical_advances={noncanonical_advances} "
        f"budget_checks={inconsistent_checked} "
        "soundness_verified=true exact_crosscheck=true"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--model", default="gpt-oss:20b")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--catalog-seed", type=int, default=920101)
    parser.add_argument("--order-seed", type=int, default=920102)
    parser.add_argument("--count", type=int, default=20)
    parser.add_argument("--composition-arity", type=int, default=3)
    parser.add_argument("--num-predict", type=int, default=1024)
    parser.add_argument("--silent-round-cap", type=int, default=3)
    # Reasoning-effort control. Omitting it reproduces a version-3 request
    # exactly; version 4 runs at low effort.
    parser.add_argument("--think", choices=["low", "medium"], default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not 1 <= args.count <= 60:
        raise PilotError("count must be in 1..60")
    if not 2 <= args.composition_arity <= 4:
        raise PilotError("composition_arity must be in 2..4")
    if args.num_predict not in (1024, 2048):
        raise PilotError("num_predict must be the initial 1024 or the repair 2048")
    if not 1 <= args.silent_round_cap <= 3:
        raise PilotError("silent_round_cap must be in 1..3")
    if not args.self_test and args.output is None:
        raise PilotError("--output is required outside --self-test")
    max_rounds = round_ceiling(args.composition_arity)
    started = time.monotonic()
    tasks, export_wall_seconds = load_tasks(
        args.catalog_seed,
        args.order_seed,
        3 if args.self_test else args.count,
        args.composition_arity,
    )
    if args.self_test:
        self_test(tasks, args.composition_arity)
        return 0

    outcomes = []
    for index, task in enumerate(tasks):
        outcome = run_task(
            args.model, task, max_rounds, args.silent_round_cap,
            args.num_predict, args.think
        )
        outcomes.append(outcome)
        print(
            f"task={index + 1}/{len(tasks)} "
            f"accepted={str(outcome['accepted']).lower()} "
            f"components={outcome['components_completed']}/"
            f"{outcome['components_total']} rounds={outcome['rounds']} "
            f"silent={outcome['silent_rounds']} calls={outcome['tool_calls']} "
            f"reason={outcome['end_reason']}",
            flush=True,
        )
    accepted = sum(int(outcome["accepted"]) for outcome in outcomes)
    success_rate = accepted / len(outcomes)
    live_episodes = sum(
        int(outcome["schema_conformant_calls"] > 0) for outcome in outcomes
    )
    liveness_rate = live_episodes / len(outcomes)
    liveness_passed = liveness_rate >= 0.90
    frontier_passed = 0.25 <= success_rate <= 0.75
    if not liveness_passed:
        decision = "interaction_liveness_failure"
    elif frontier_passed:
        decision = "within_frontier"
    elif success_rate < 0.25:
        decision = "below_frontier"
    else:
        decision = "above_frontier"
    show = post_json("/api/show", {"model": args.model}, timeout=60)
    tags = get_json("/api/tags").get("models", [])
    tag = next((item for item in tags if item.get("name") == args.model), {})
    running = get_json("/api/ps").get("models", [])
    loaded = next((item for item in running if item.get("name") == args.model), {})
    report = {
        "schema": "gene.component_workflow_difficulty_pilot.v1",
        "date_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "harness_sha256": sha256_file(Path(__file__).resolve()),
        "exporter_sha256": sha256_file(EXPORTER),
        "subject_sha256": sha256_file(SUBJECT),
        "base_subject_sha256": sha256_file(BASE_SUBJECT),
        "interpreter_sha256": sha256_file(INTERPRETER),
        "model": {
            "name": args.model,
            "manifest_digest": tag.get("digest"),
            "capabilities": show.get("capabilities"),
            "loaded_size_bytes": loaded.get("size"),
            "loaded_vram_bytes": loaded.get("size_vram"),
        },
        "seeds": {
            "catalog": args.catalog_seed,
            "order_and_cases": args.order_seed,
            "permanently_excluded": True,
        },
        "composition_arity": args.composition_arity,
        "attempts_per_component": tasks[0]["attempts_per_component"],
        "model_facing_tools": sorted(
            tool["function"]["name"] for tool in TOOLS
        ),
        "model_visible_task_fields": sorted(PUBLIC_TASK_FIELDS),
        "model_hidden_task_fields": sorted(HIDDEN_TASK_FIELDS),
        "decoding": {
            "temperature": 0,
            "seed": 20260809,
            "num_ctx": 32768,
            "num_predict": args.num_predict,
            "reasoning_effort": args.think or "default",
            "max_rounds": max_rounds,
            "silent_round_cap": args.silent_round_cap,
        },
        "gate": {
            "minimum_liveness_rate": 0.90,
            "liveness_rate": liveness_rate,
            "liveness_passed": liveness_passed,
            "minimum_success_rate": 0.25,
            "maximum_success_rate": 0.75,
            "frontier_passed": frontier_passed,
            "decision": decision,
            "passed": liveness_passed and frontier_passed,
        },
        "summary": {
            "tasks": len(outcomes),
            "accepted": accepted,
            "success_rate": success_rate,
            "live_episodes": live_episodes,
            "rounds": sum(item["rounds"] for item in outcomes),
            "silent_rounds": sum(item["silent_rounds"] for item in outcomes),
            "tool_calls": sum(item["tool_calls"] for item in outcomes),
            "schema_conformant_calls": sum(
                item["schema_conformant_calls"] for item in outcomes
            ),
            "checker_attempts": sum(item["checker_attempts"] for item in outcomes),
            "components_completed": sum(
                item["components_completed"] for item in outcomes
            ),
            "components_total": sum(item["components_total"] for item in outcomes),
            "hidden_reads": sum(item["hidden_reads"] for item in outcomes),
            "prompt_tokens": sum(item["prompt_tokens"] for item in outcomes),
            "generated_tokens": sum(item["generated_tokens"] for item in outcomes),
            "export_wall_seconds": export_wall_seconds,
            "total_wall_seconds": time.monotonic() - started,
            "harness_peak_rss_bytes": peak_rss_bytes(),
        },
        "outcomes": outcomes,
    }
    assert args.output is not None
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        f"liveness gate: live={live_episodes}/{len(outcomes)} "
        f"rate={liveness_rate:.3f} passed={str(liveness_passed).lower()}"
    )
    print(
        f"difficulty gate: accepted={accepted}/{len(outcomes)} "
        f"rate={success_rate:.3f} decision={decision}"
    )
    return 0 if liveness_passed and frontier_passed else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (PilotError, OSError, subprocess.TimeoutExpired) as exc:
        print(f"component workflow pilot error: {exc}", file=sys.stderr)
        raise SystemExit(2)
