#!/usr/bin/env python3
"""Stage-three qualification: per-component accuracy inside a full episode.

Stage two isolates one component and over-predicted subject accuracy roughly
4.7-fold: it measured `0.583` per component for `gpt-oss:20b` at low reasoning
effort where the version-4 subject delivered `0.125`. The obvious explanation,
that stage two's hand-picked programs were shallower than the subject's screened
depth-three families, was tested and refuted -- eleven of the twelve have
minimum finite-bank depth three.

What remains is episode framing. A stage-two round shows one component's three
demonstrations and nothing else. A subject round shows two components in order,
both demonstration packs, a query input, and an accumulating transcript, and
requires selecting the current component before inferring it.

This stage holds the programs and demonstrations **identical to stage two** and
varies only the framing, so the comparison isolates episode context rather than
task difficulty. It reuses the subject's exact tool names, schemas, public
checker semantics, and budgets, so the adapter is the same one the subject uses.

The twelve programs and all episodes here are permanently excluded from every
experiment.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import resource
import statistics
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


OLLAMA_URL = "http://127.0.0.1:11434"
OPERATIONS = [
    "tail",
    "init",
    "reverse",
    "rotate_left",
    "rotate_right",
    "map_add_one",
    "map_sub_one",
    "map_double",
    "map_negate",
    "keep_even",
    "keep_odd",
    "duplicate_each",
]
OPERATION_HELP = {
    "tail": "remove the first item",
    "init": "remove the last item",
    "reverse": "reverse item order",
    "rotate_left": "move the first item to the end",
    "rotate_right": "move the last item to the front",
    "map_add_one": "add one to every item",
    "map_sub_one": "subtract one from every item",
    "map_double": "double every item",
    "map_negate": "negate every item",
    "keep_even": "keep only even items",
    "keep_odd": "keep only odd items",
    "duplicate_each": "duplicate every item in place",
}
COMPONENT_OPERATION_COUNT = 3
# Deliberately byte-identical to the stage-two harness so the only variable
# between the two stages is episode framing.
DEMONSTRATION_INPUTS = [
    [2, -1, 3, 0, 4],
    [-2, 5, 1, -3],
    [3, 3, -2, 1, 0],
]
HIDDEN_PROGRAMS = [
    ("tail", "reverse", "map_add_one"),
    ("init", "map_double", "keep_even"),
    ("rotate_left", "map_negate", "duplicate_each"),
    ("rotate_right", "keep_odd", "map_sub_one"),
    ("map_double", "map_add_one", "reverse"),
    ("duplicate_each", "tail", "map_negate"),
    ("keep_even", "rotate_right", "map_double"),
    ("map_sub_one", "keep_odd", "init"),
    ("reverse", "rotate_left", "map_sub_one"),
    ("map_negate", "duplicate_each", "keep_even"),
    ("tail", "init", "rotate_right"),
    ("keep_odd", "map_add_one", "rotate_left"),
]
# Ten ordered pairs covering all twelve programs, giving twenty components.
EPISODE_PAIRS = [
    (0, 1),
    (2, 3),
    (4, 5),
    (6, 7),
    (8, 9),
    (10, 11),
    (1, 2),
    (3, 4),
    (5, 6),
    (7, 8),
]
QUERY_INPUT_POOL = [
    [3, -4, -2, 0, 1, -2, 1, 5],
    [2, 5, -3, 1, 4, 0, -1, 3, 2],
    [-1, 4, 2, -5, 0, 3, 1, -2, 4, 1],
    [5, -2, 3, 0, -4, 2, 1, -3, 5, 0, 2],
    [1, 2, -1, 4, -3, 0, 5, -2, 3, 1, -4, 2],
    [4, 1, -3, 2, 0, -1, 3, 5, -2, 1],
]
ATTEMPTS_PER_COMPONENT = 2
SILENT_ROUND_CAP = 3
NUM_PREDICT = 1024
MINIMUM_LIVENESS_RATE = 0.90
PUBLIC_TASK_FIELDS = {
    "task_id",
    "instruction",
    "components_in_order",
    "query_input",
    "attempts_per_component",
}
HIDDEN_TASK_FIELDS = {"expected", "component_operations", "chain_values"}
CHECKER_RESPONSE_FIELDS = {
    "status",
    "components_completed",
    "components_remaining",
    "current",
    "attempts_remaining",
}
INSTRUCTION = (
    "Identify each listed workflow from its three demonstrations, then send "
    "exactly three catalog operations for it to apply_workflow_candidate. "
    "Complete the components in the order given, then call submit_result once."
)
SYSTEM_PROMPT = """Identify demonstration-defined list workflows one component
at a time. Every component is generated by exactly three operations from this
catalog:
{catalog}
Work through the listed components in the given order. For the current
component, infer its three operations from its three demonstrations and send
them with apply_workflow_candidate. The checker runs your three operations on
those same three public demonstrations and nothing else. If all three
reproduce, the component is accepted and the host applies your operations to
the query list. Otherwise you get status inconsistent and one further attempt;
when a component's attempt budget is spent the task ends.
Call submit_result once, after the last component is accepted. It is final: the
first submit_result ends the task whether the answer is right or wrong.
Several tool calls may share one response. Your response is cut off at a hard
generation limit, so keep reasoning short and return a tool call in every
response; a response with no tool call wastes a round.""".format(
    catalog="; ".join(f"{name}: {OPERATION_HELP[name]}" for name in OPERATIONS)
)
SILENT_ROUND_REMINDER = (
    "Your previous response reached the generation limit without a tool call. "
    "Do not restate your reasoning. Send apply_workflow_candidate now for the "
    "first component that has not been accepted, using your best three "
    "operations."
)
APPLY_TOOL = {
    "type": "function",
    "function": {
        "name": "apply_workflow_candidate",
        "description": (
            "Propose the three catalog operations for the current workflow "
            "component. Checked against that component's three public "
            "demonstrations only."
        ),
        "parameters": {
            "type": "object",
            "additionalProperties": False,
            "required": ["workflow_id", "operations"],
            "properties": {
                "workflow_id": {"type": "string"},
                "operations": {
                    "type": "array",
                    "description": "Exactly three catalog operations, in order.",
                    "items": {"type": "string", "enum": OPERATIONS},
                },
            },
        },
    },
}
SUBMIT_TOOL = {
    "type": "function",
    "function": {
        "name": "submit_result",
        "description": (
            "Submit the host-maintained query list for the final exact check. "
            "This ends the task."
        ),
        "parameters": {
            "type": "object",
            "additionalProperties": False,
            "properties": {},
        },
    },
}
TOOLS = [APPLY_TOOL, SUBMIT_TOOL]
TRANSPORT_ATTEMPTS = 3
TRANSPORT_BACKOFF_SECONDS = (2.0, 4.0)
TRANSPORT_RETRIES = 0


class QualificationError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def post_json(path: str, payload: dict[str, Any], timeout: int = 300) -> dict[str, Any]:
    global TRANSPORT_RETRIES
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    last: Exception | None = None
    for attempt in range(TRANSPORT_ATTEMPTS):
        request = urllib.request.Request(
            OLLAMA_URL + path,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                return json.loads(response.read().decode("utf-8"))
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as error:
            last = error
            if attempt + 1 == TRANSPORT_ATTEMPTS:
                break
            TRANSPORT_RETRIES += 1
            time.sleep(TRANSPORT_BACKOFF_SECONDS[attempt])
    raise QualificationError(f"transport failed after {TRANSPORT_ATTEMPTS}: {last}")


def get_json(path: str) -> dict[str, Any]:
    with urllib.request.urlopen(OLLAMA_URL + path, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def apply_operation(value: list[int], operation: str) -> list[int]:
    if operation == "tail":
        return value[1:] if len(value) > 1 else []
    if operation == "init":
        return value[:-1] if len(value) > 1 else []
    if operation == "reverse":
        return list(reversed(value))
    if operation == "rotate_left":
        return value[1:] + value[:1] if len(value) > 1 else list(value)
    if operation == "rotate_right":
        return value[-1:] + value[:-1] if len(value) > 1 else list(value)
    if operation == "map_add_one":
        return [item + 1 for item in value]
    if operation == "map_sub_one":
        return [item - 1 for item in value]
    if operation == "map_double":
        return [item * 2 for item in value]
    if operation == "map_negate":
        return [-item for item in value]
    if operation == "keep_even":
        return [item for item in value if item % 2 == 0]
    if operation == "keep_odd":
        return [item for item in value if item % 2 != 0]
    if operation == "duplicate_each":
        return [copy for item in value for copy in (item, item)]
    raise QualificationError("unknown operation reached the exact executor")


def apply_program(value: list[int], operations: list[str]) -> list[int]:
    result = list(value)
    for operation in operations:
        result = apply_operation(result, operation)
    return result


def enumerate_programs(maximum_length: int = COMPONENT_OPERATION_COUNT) -> list[tuple]:
    programs: list[tuple] = [()]
    frontier: list[tuple] = [()]
    for _ in range(maximum_length):
        extended = [prefix + (name,) for prefix in frontier for name in OPERATIONS]
        programs.extend(extended)
        frontier = extended
    return programs


ALL_PROGRAMS = enumerate_programs()


def demonstrations_for(program: tuple) -> list[dict[str, Any]]:
    return [
        {"input": value, "output": apply_program(value, list(program))}
        for value in DEMONSTRATION_INPUTS
    ]


def admissible_for(demonstrations: list[dict[str, Any]]) -> list[tuple]:
    return [
        candidate
        for candidate in ALL_PROGRAMS
        if all(
            apply_program(item["input"], list(candidate)) == item["output"]
            for item in demonstrations
        )
    ]


ADMISSIBLE = [admissible_for(demonstrations_for(p)) for p in HIDDEN_PROGRAMS]


def build_episodes() -> list[dict[str, Any]]:
    """One episode per ordered pair, using the first pooled query input for
    which both components change the value, the final output is nonempty, and
    the public-checker soundness rule holds: every publicly admissible candidate
    must agree with the hidden program on the exact chain value it receives."""
    episodes = []
    for index, (first, second) in enumerate(EPISODE_PAIRS):
        chosen = None
        for query in QUERY_INPUT_POOL:
            chain = [query]
            ok = True
            for slot in (first, second):
                nxt = apply_program(chain[-1], list(HIDDEN_PROGRAMS[slot]))
                if nxt == chain[-1] or not nxt:
                    ok = False
                    break
                for candidate in ADMISSIBLE[slot]:
                    if apply_program(chain[-1], list(candidate)) != nxt:
                        ok = False
                        break
                if not ok:
                    break
                chain.append(nxt)
            if ok and chain[-1] != query:
                chosen = (query, chain)
                break
        if chosen is None:
            raise QualificationError(
                f"no pooled query input satisfies episode {index}"
            )
        query, chain = chosen
        episodes.append(
            {
                "id": f"episode_{index:02d}",
                "component_slots": [first, second],
                "components": [
                    {
                        "workflow_id": f"workflow_{slot:02d}",
                        "demonstrations": demonstrations_for(HIDDEN_PROGRAMS[slot]),
                    }
                    for slot in (first, second)
                ],
                "query_input": query,
                "chain_values": chain,
                "expected": chain[-1],
                "component_operations": [
                    list(HIDDEN_PROGRAMS[slot]) for slot in (first, second)
                ],
            }
        )
    return episodes


def public_projection(episode: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": episode["id"],
        "instruction": INSTRUCTION,
        "components_in_order": episode["components"],
        "query_input": episode["query_input"],
        "attempts_per_component": ATTEMPTS_PER_COMPONENT,
    }


class PublicChecker:
    def __init__(self, projection: dict[str, Any]) -> None:
        if set(projection) != PUBLIC_TASK_FIELDS:
            raise QualificationError("public checker received a non-public projection")
        self.components = projection["components_in_order"]
        self.attempts_per_component = projection["attempts_per_component"]
        self.current = list(projection["query_input"])
        self.component_index = 0
        self.attempts_used = 0
        self.checker_attempts = 0

    @property
    def finished(self) -> bool:
        return self.component_index >= len(self.components)

    def well_formed(self, workflow_id: Any, operations: Any) -> bool:
        return (
            not self.finished
            and isinstance(workflow_id, str)
            and workflow_id == self.components[self.component_index]["workflow_id"]
            and isinstance(operations, list)
            and len(operations) == COMPONENT_OPERATION_COUNT
            and all(isinstance(i, str) and i in OPERATIONS for i in operations)
        )

    def apply_candidate(self, workflow_id: Any, operations: Any) -> dict[str, Any]:
        if not self.well_formed(workflow_id, operations):
            return {"status": "invalid_request"}
        component = self.components[self.component_index]
        self.checker_attempts += 1
        self.attempts_used += 1
        candidate = list(operations)
        if all(
            apply_program(item["input"], candidate) == item["output"]
            for item in component["demonstrations"]
        ):
            self.current = apply_program(self.current, candidate)
            self.component_index += 1
            self.attempts_used = 0
            return {
                "status": "accepted",
                "components_completed": self.component_index,
                "components_remaining": len(self.components) - self.component_index,
                "current": self.current,
            }
        if self.attempts_used >= self.attempts_per_component:
            return {"status": "attempts_exhausted"}
        return {
            "status": "inconsistent",
            "attempts_remaining": self.attempts_per_component - self.attempts_used,
        }


def schema_conformant(name: Any, arguments: Any) -> bool:
    if name == "apply_workflow_candidate":
        return (
            isinstance(arguments, dict)
            and set(arguments) == {"workflow_id", "operations"}
            and isinstance(arguments["workflow_id"], str)
            and isinstance(arguments["operations"], list)
            and len(arguments["operations"]) == COMPONENT_OPERATION_COUNT
            and all(
                isinstance(i, str) and i in OPERATIONS
                for i in arguments["operations"]
            )
        )
    if name == "submit_result":
        return isinstance(arguments, dict) and not arguments
    return False


def round_ceiling(component_count: int) -> int:
    return 3 * component_count + 3


def chat_payload(
    model: str, messages: list[dict[str, Any]], num_predict: int, think: str | None
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "tools": TOOLS,
        "stream": False,
        "keep_alive": "10m",
        "options": {
            "temperature": 0,
            "seed": 20260809,
            "num_ctx": 32768,
            "num_predict": num_predict,
        },
    }
    if think is not None:
        payload["think"] = think
    return payload


def run_episode(
    model: str, episode: dict[str, Any], num_predict: int, think: str | None
) -> dict[str, Any]:
    projection = public_projection(episode)
    user_message = canonical_json(projection)
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_message},
    ]
    checker = PublicChecker(projection)
    max_rounds = round_ceiling(len(episode["components"]))
    accepted = False
    end_reason = "round_limit"
    silent_rounds = 0
    tool_calls = 0
    conformant_calls = 0
    prompt_tokens = 0
    generated_tokens = 0
    round_tokens: list[int] = []
    rounds = 0
    finished = False
    started = time.monotonic()
    for rounds in range(1, max_rounds + 1):
        response = post_json(
            "/api/chat", chat_payload(model, messages, num_predict, think)
        )
        prompt_tokens += int(response.get("prompt_eval_count", 0))
        emitted = int(response.get("eval_count", 0))
        generated_tokens += emitted
        round_tokens.append(emitted)
        message = response.get("message")
        if not isinstance(message, dict):
            end_reason = "empty_response"
            break
        messages.append(message)
        calls = message.get("tool_calls") or []
        if not isinstance(calls, list) or not calls:
            silent_rounds += 1
            if silent_rounds > SILENT_ROUND_CAP:
                end_reason = "silent_round_limit"
                break
            messages.append({"role": "user", "content": SILENT_ROUND_REMINDER})
            continue
        for call in calls:
            tool_calls += 1
            function = call.get("function") if isinstance(call, dict) else None
            name = function.get("name") if isinstance(function, dict) else None
            arguments = function.get("arguments") if isinstance(function, dict) else None
            conformant = schema_conformant(name, arguments)
            conformant_calls += int(conformant)
            if name == "apply_workflow_candidate":
                result = (
                    checker.apply_candidate(
                        arguments["workflow_id"], arguments["operations"]
                    )
                    if conformant
                    else {"status": "invalid_request"}
                )
                if result["status"] == "attempts_exhausted":
                    end_reason = "attempts_exhausted"
                    finished = True
            elif name == "submit_result" and conformant:
                accepted = checker.current == episode["expected"]
                result = {"status": "accepted" if accepted else "rejected"}
                end_reason = "submitted"
                finished = True
            else:
                result = {"status": "invalid_request"}
            if set(result) - CHECKER_RESPONSE_FIELDS:
                raise QualificationError("a tool response carried an undeclared field")
            messages.append(
                {
                    "role": "tool",
                    "tool_name": name if isinstance(name, str) else "invalid_tool",
                    "content": json.dumps(result, sort_keys=True),
                }
            )
            if finished:
                break
        if finished:
            break
    return {
        "id": episode["id"],
        "accepted": accepted,
        "end_reason": end_reason,
        "rounds": rounds,
        "silent_rounds": silent_rounds,
        "tool_calls": tool_calls,
        "schema_conformant_calls": conformant_calls,
        "checker_attempts": checker.checker_attempts,
        "components_completed": checker.component_index,
        "components_total": len(episode["components"]),
        "prompt_tokens": prompt_tokens,
        "generated_tokens": generated_tokens,
        "generated_tokens_per_round": round_tokens,
        "wall_seconds": time.monotonic() - started,
    }


def peak_rss_bytes() -> int:
    value = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return int(value if platform.system() == "Darwin" else value * 1024)


def percentile(values: list[float], fraction: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    return float(ordered[min(len(ordered) - 1, int(round(fraction * (len(ordered) - 1))))])


def self_test(episodes: list[dict[str, Any]]) -> None:
    if PUBLIC_TASK_FIELDS & HIDDEN_TASK_FIELDS:
        raise QualificationError("public and hidden field sets overlap")
    if {t["function"]["name"] for t in TOOLS} != {
        "apply_workflow_candidate",
        "submit_result",
    }:
        raise QualificationError("tool set is not the subject's declared pair")
    covered = {slot for pair in EPISODE_PAIRS for slot in pair}
    if covered != set(range(len(HIDDEN_PROGRAMS))):
        raise QualificationError("episodes do not cover every hidden program")
    components = sum(len(e["components"]) for e in episodes)
    for episode in episodes:
        projection = public_projection(episode)
        message = canonical_json(projection)
        for field in HIDDEN_TASK_FIELDS:
            if field in message:
                raise QualificationError("public projection names a hidden field")
        for value in episode["chain_values"][1:]:
            if canonical_json(value) in message:
                raise QualificationError("public projection leaked a chain value")
        checker = PublicChecker(projection)
        for index, slot in enumerate(episode["component_slots"]):
            candidates = ADMISSIBLE[slot]
            canonical = tuple(HIDDEN_PROGRAMS[slot])
            # Only exactly-three-operation candidates can cross the tool. The
            # admissible set also contains shorter programs whenever a hidden
            # program collapses below depth three, and those are unreachable.
            chosen = next(
                (
                    c
                    for c in candidates
                    if c != canonical and len(c) == COMPONENT_OPERATION_COUNT
                ),
                canonical,
            )
            result = checker.apply_candidate(
                episode["components"][index]["workflow_id"], list(chosen)
            )
            if result["status"] != "accepted":
                raise QualificationError("an admissible candidate failed to advance")
            if result["current"] != episode["chain_values"][index + 1]:
                raise QualificationError("an accepted candidate diverged from the chain")
        if not checker.finished or checker.current != episode["expected"]:
            raise QualificationError("the public path did not reach the hidden output")
        checker = PublicChecker(projection)
        first = episode["components"][0]
        wrong = ["reverse", "reverse", "reverse"]
        if checker.apply_candidate(first["workflow_id"], wrong) != {
            "status": "inconsistent",
            "attempts_remaining": 1,
        }:
            raise QualificationError("an inconsistent candidate leaked detail")
        if checker.apply_candidate(first["workflow_id"], wrong) != {
            "status": "attempts_exhausted"
        }:
            raise QualificationError("the attempt budget is not exact")
        if checker.component_index != 0:
            raise QualificationError("an inconsistent candidate advanced a component")
    print(
        "episode depth gate self-test: "
        f"episodes={len(episodes)} components={components} "
        f"round_ceiling={round_ceiling(2)} attempts={ATTEMPTS_PER_COMPONENT} "
        f"public_hidden_fields=0 soundness_verified=true "
        "framing=episode programs=stage_two_identical"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--model", default="gpt-oss:20b")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--num-predict", type=int, default=NUM_PREDICT)
    parser.add_argument("--think", choices=["low", "medium"], default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.self_test and args.output is None:
        raise QualificationError("--output is required outside --self-test")
    episodes = build_episodes()
    if args.self_test:
        self_test(episodes)
        return 0

    started = time.monotonic()
    outcomes = []
    for index, episode in enumerate(episodes):
        outcome = run_episode(args.model, episode, args.num_predict, args.think)
        outcomes.append(outcome)
        print(
            f"episode={index + 1}/{len(episodes)} "
            f"accepted={str(outcome['accepted']).lower()} "
            f"components={outcome['components_completed']}/"
            f"{outcome['components_total']} rounds={outcome['rounds']} "
            f"silent={outcome['silent_rounds']} reason={outcome['end_reason']}",
            flush=True,
        )
    components_completed = sum(o["components_completed"] for o in outcomes)
    components_total = sum(o["components_total"] for o in outcomes)
    component_rate = components_completed / components_total
    accepted = sum(int(o["accepted"]) for o in outcomes)
    live = sum(int(o["schema_conformant_calls"] > 0) for o in outcomes)
    liveness_rate = live / len(outcomes)
    rounds = sum(o["rounds"] for o in outcomes)
    silent = sum(o["silent_rounds"] for o in outcomes)
    per_round = [v for o in outcomes for v in o["generated_tokens_per_round"]]
    show = post_json("/api/show", {"model": args.model}, timeout=60)
    tags = get_json("/api/tags").get("models", [])
    tag = next((i for i in tags if i.get("name") == args.model), {})
    report = {
        "schema": "gene.episode_depth_qualification.v1",
        "date_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "harness_sha256": sha256_file(Path(__file__).resolve()),
        "model": {
            "name": args.model,
            "manifest_digest": tag.get("digest"),
            "capabilities": show.get("capabilities"),
        },
        "stage": {
            "episodes": len(episodes),
            "components_per_episode": 2,
            "operations_per_component": COMPONENT_OPERATION_COUNT,
            "attempts_per_component": ATTEMPTS_PER_COMPONENT,
            "round_ceiling": round_ceiling(2),
            "silent_round_cap": SILENT_ROUND_CAP,
            "programs_identical_to_stage_two": True,
            "permanently_excluded": True,
        },
        "decoding": {
            "temperature": 0,
            "seed": 20260809,
            "num_ctx": 32768,
            "num_predict": args.num_predict,
            "reasoning_effort": args.think or "default",
        },
        "summary": {
            "episodes": len(outcomes),
            "accepted_episodes": accepted,
            "episode_success_rate": accepted / len(outcomes),
            "components_completed": components_completed,
            "components_total": components_total,
            "per_component_solve_rate": component_rate,
            "live_episodes": live,
            "liveness_rate": liveness_rate,
            "rounds": rounds,
            "silent_rounds": silent,
            "silent_round_fraction": silent / rounds if rounds else 0.0,
            "tool_calls": sum(o["tool_calls"] for o in outcomes),
            "schema_conformant_calls": sum(
                o["schema_conformant_calls"] for o in outcomes
            ),
            "checker_attempts": sum(o["checker_attempts"] for o in outcomes),
            "prompt_tokens": sum(o["prompt_tokens"] for o in outcomes),
            "generated_tokens": sum(o["generated_tokens"] for o in outcomes),
            "generated_tokens_per_round_mean": (
                statistics.fmean(per_round) if per_round else 0.0
            ),
            "generated_tokens_per_round_p95": percentile(per_round, 0.95),
            "transport_retries": TRANSPORT_RETRIES,
            "total_wall_seconds": time.monotonic() - started,
            "harness_peak_rss_bytes": peak_rss_bytes(),
        },
        "outcomes": outcomes,
    }
    assert args.output is not None
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        f"liveness: live={live}/{len(outcomes)} rate={liveness_rate:.3f} "
        f"passed={str(liveness_rate >= MINIMUM_LIVENESS_RATE).lower()}"
    )
    print(
        f"per-component solve: {components_completed}/{components_total} "
        f"rate={component_rate:.3f}"
    )
    print(
        f"episode success: {accepted}/{len(outcomes)} "
        f"rate={accepted / len(outcomes):.3f}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (QualificationError, OSError) as exc:
        print(f"episode depth qualification error: {exc}", file=sys.stderr)
        raise SystemExit(2)
