// Generated by tools/generate_dom_bindings.mjs from TypeScript 5.9.2.
// This is the intentionally supported subset, not a claim to model all lib.dom.d.ts.
export interface GeneDomBindings {
  create_element(document: Document, tag_name: string): Element;
  create_text_node(document: Document, text: string): Text;
  create_document_fragment(document: Document): DocumentFragment;
  append_child(parent: Node, child: Node): Node;
  remove_child(parent: Node, child: Node): Node;
  set_attribute(element: Element, name: string, value: string): void;
  remove_attribute(element: Element, name: string): void;
  add_event_listener(target: EventTarget, type: string, listener: (event: Event) => void): void;
  remove_event_listener(target: EventTarget, type: string, listener: (event: Event) => void): void;
}
